// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using myWpf;

#nullable disable

namespace myWpf.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221121004657_n27")]
    partial class n27
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("myWpf.Gorod", b =>
                {
                    b.Property<int>("IdGorod")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.HasKey("IdGorod");

                    b.ToTable("gorod");
                });

            modelBuilder.Entity("myWpf.Postav", b =>
                {
                    b.Property<int>("IdPostav")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    b.Property<int>("GorodId")
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("Telef")
                        .IsRequired()
                        .HasColumnType("VARCHAR(15)");

                    b.Property<int>("UlicaId")
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    b.HasKey("IdPostav");

                    b.HasIndex("GorodId");

                    b.HasIndex("UlicaId");

                    b.ToTable("postav");
                });

            modelBuilder.Entity("myWpf.Prihod", b =>
                {
                    b.Property<int>("IdPrihod")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    b.Property<DateTime>("DatPrih")
                        .HasColumnType("DATE");

                    b.Property<int>("Kolvo")
                        .HasColumnType("INT(4)");

                    b.Property<int>("PostavId")
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    b.Property<int>("TovarId")
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    b.HasKey("IdPrihod");

                    b.HasIndex("PostavId");

                    b.HasIndex("TovarId");

                    b.ToTable("prihod");
                });

            modelBuilder.Entity("myWpf.Tovar", b =>
                {
                    b.Property<int>("IdTovar")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    b.Property<int>("Cena")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<string>("Edizm")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.HasKey("IdTovar");

                    b.ToTable("tovar");
                });

            modelBuilder.Entity("myWpf.Ulica", b =>
                {
                    b.Property<int>("IdUlica")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.HasKey("IdUlica");

                    b.ToTable("ulica");
                });

            modelBuilder.Entity("myWpf.Postav", b =>
                {
                    b.HasOne("myWpf.Gorod", "Gorod")
                        .WithMany("PostavG")
                        .HasForeignKey("GorodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("myWpf.Ulica", "Ulica")
                        .WithMany("PostavU")
                        .HasForeignKey("UlicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gorod");

                    b.Navigation("Ulica");
                });

            modelBuilder.Entity("myWpf.Prihod", b =>
                {
                    b.HasOne("myWpf.Postav", "Postav")
                        .WithMany("Prihod")
                        .HasForeignKey("PostavId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("myWpf.Tovar", "Tovar")
                        .WithMany("Prihod")
                        .HasForeignKey("TovarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Postav");

                    b.Navigation("Tovar");
                });

            modelBuilder.Entity("myWpf.Gorod", b =>
                {
                    b.Navigation("PostavG");
                });

            modelBuilder.Entity("myWpf.Postav", b =>
                {
                    b.Navigation("Prihod");
                });

            modelBuilder.Entity("myWpf.Tovar", b =>
                {
                    b.Navigation("Prihod");
                });

            modelBuilder.Entity("myWpf.Ulica", b =>
                {
                    b.Navigation("PostavU");
                });
#pragma warning restore 612, 618
        }
    }
}
