// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using myWpf;

#nullable disable

namespace myWpf.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221022013957_n3")]
    partial class n3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("myWpf.Goods", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("goods3");
                });

            modelBuilder.Entity("myWpf.Postav", b =>
                {
                    b.Property<int>("IdPostav")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    b.Property<int>("IdGorod")
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    b.Property<int>("IdUlica")
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("Telef")
                        .IsRequired()
                        .HasColumnType("VARCHAR(15)");

                    b.HasKey("IdPostav");

                    b.ToTable("postav");
                });

            modelBuilder.Entity("myWpf.Prihod", b =>
                {
                    b.Property<int>("IdPrihod")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    b.Property<DateTime>("DatPrih")
                        .HasColumnType("DATE");

                    b.Property<int>("IdPostav")
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    b.Property<int>("IdTovar")
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    b.Property<int>("Kolvo")
                        .HasColumnType("INT(4)");

                    b.HasKey("IdPrihod");

                    b.ToTable("prihod");
                });

            modelBuilder.Entity("myWpf.Tovar", b =>
                {
                    b.Property<int>("IdTovar")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    b.Property<int>("Cena")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<string>("Edizm")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.HasKey("IdTovar");

                    b.ToTable("tovar");
                });
#pragma warning restore 612, 618
        }
    }
}
